nwg_exceptions: add missing header after 4487a2399281
common/nwg_exceptions.cc:16:5: error: use of undeclared identifier 'errno'
    errno = 0;
    ^
common/nwg_exceptions.cc:18:18: error: use of undeclared identifier 'errno'
    if (!cstr || errno) {
                 ^