common: add missing header for libc++ >= 13
In file included from bar/bar.cc:12:
common/nwg_classes.h:200:33: error: no viable constructor or deduction guide for deduction of template arguments of 'array'
    static constexpr std::array MAGIC { 'i', '3', '-', 'i', 'p', 'c' };
                                ^
/usr/include/c++/v1/__tuple:219:64: note: candidate function template not viable: requires 1 argument, but 6 were provided
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
                                                               ^
/usr/include/c++/v1/__tuple:219:64: note: candidate function template not viable: requires 0 arguments, but 6 were provided